apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillpulse-production

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: skillpulse-production
    target:
      kind: Namespace

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment

labels:
  - pairs:
      environment: production

images:
  - name: trainwithshubham/skillpulse-backend
    newTag: latest
  - name: trainwithshubham/skillpulse-frontend
    newTag: latest
